- README.md
Both Zebra and ZCash links were pointing at the ZCash repo. This updates the Zebra link to point at the Zebra repo.
> fix: README zebra link pointing at zcash

- src/protocol/payload/mod.rs
- src/protocol/payload/tx.rs
This PR implements encoding and decoding for V1 -> V4 transactions (V5 isn't yet stable) as per [the Zcash spec](https://zips.z.cash/protocol/canopy.pdf#consensusfrombitcoin). 
This PR also features very simple round trip unit tests (ignored by default). In future more rigourous testing should be considered.
> Transaction encoding and decoding

- src/helpers.rs
- src/lib.rs
- src/setup/node.rs
- src/tests/conformance/handshake.rs
- src/tests/conformance/messages.rs
This PR:
- introduces a `helpers` module to be used for general test heper code until we find a better structure for it,
- relies on peer connection to signal node startup completion (could be further improved, for now this is done manually in tests),
- introduces the `wait_until!` macro—useful for message filtering,
- makes test naming and ordering consistent.
> Improve node startup and handshake

- src/setup/config.rs
- src/setup/node.rs
- src/tests/conformance/handshake.rs
This PR abstracts node start signalling through a peer connection. Note the address from the `Config` still needs to be passed in at this stage.
> Node start signalling

- README.md
Was pointing at ZCashFoundation, which is roughly ~2k commits behind.
> fix: readme link to zcash

- src/setup/config.rs
This allows us to circumvent our chain being too short checks.
All tests that were green, are still green.
> feat: zcash now uses whitebind instead of bind

- src/protocol/message.rs
- src/protocol/payload/addr.rs
- src/protocol/payload/block.rs
- src/protocol/payload/codec.rs
- src/protocol/payload/inv.rs
- src/protocol/payload/mod.rs
- src/protocol/payload/reject.rs
- src/protocol/payload/tx.rs
- src/protocol/payload/version.rs
The spec states that the `tx_count` is always zero when transmitted in the Header message.
This removes the `tx_count` from the header field, instead opting to encode / decode the VarInt according to its purpose at the next highest level.
So for a `Block` message it will encode the actual tx count, and for `Headers` each `Header` will have a `VarInt(0)` appended.
> fix: Header tx_count must be zero for encoding

- README.md
- src/helpers.rs
- src/protocol/message.rs
- src/tests/conformance/handshake.rs
- src/tests/conformance/messages.rs
- src/tests/mod.rs
- src/tests/resistance/fuzzing.rs
- src/tests/resistance/mod.rs
This PR introduces the first fuzz test cases. 
Included: 
- resistance-001 for all types of payloads,
- resistance-002 for all types of payloads,
- adjusts `Message` and `MessageHeader` to allow encoding/decoding without writing to stream.
- introduces various helpers for fuzzing payload creation
> test: resistance-001/002

- Cargo.toml
- src/tests/resistance/fuzzing.rs
Follow up to #29. Replaces the RNG with the seedable `ChaCha8Rng`. This makes the tests reproducable.
> ref: seedable RNG for fuzz test reproducability

- src/protocol/payload/block.rs
- src/protocol/payload/inv.rs
- src/protocol/payload/mod.rs
- src/setup/config.rs
- src/setup/node.rs
- src/tests/conformance/handshake.rs
- src/tests/conformance/messages.rs
- src/tests/resistance/fuzzing.rs
Refactors the `node.wait_for_connection` to `node.initial_action(Action)` where `Action` can be one of
1. None
2. Wait for connection
3. Seed with genesis blocks
One alternative is to create a helper function instead. I decided it would be better to have it as part of the node startup since the procedure requires that no other data has been sent to the node yet.
I'm open to changing this though.
> Add action to seed node with genesis blocks on startup

- README.md
- src/setup/config.rs
- src/setup/node.rs
- src/tests/conformance/handshake.rs
- src/tests/conformance/messages.rs
- src/tests/resistance/fuzzing.rs
This PR: 
- removes docker configuration (see readme for new format),
- removes `read_config_file` (absracted),
- changes `initial_peers` to accept full addresses instead of just the port,
- exposes `config::new_local_addr` as a convenience function,
- introduces constants for configuration file names.
> ref: remove docker configuration support

- .github/workflows/test.yml
Effectively reduces each jobs `cargo action` section from 60secs+ to <10secs (barring dependency changes).
(Not sure we actually want this - I just wanted to see the impact)
> feat: add caching to CI jobs

- README.md
- src/protocol/payload/tx.rs
- src/tests/conformance/messages.rs
- src/tests/mod.rs
Note that this includes the missing test messages for case 009.
> conformance test 010 and 009

- README.md
- src/protocol/payload/addr.rs
- src/tests/conformance/messages.rs
Note that the test case for `Addr` without a timestamp cannot be run with the code as is. This is due to the test case basically requiring a malformed struct which `encode` rejects / panics on.
> conformance test 011

- Cargo.toml
- README.md
- SPEC.md
- src/helpers/mod.rs
- src/helpers/synthetic_peers.rs
- src/protocol/message/filter.rs
- src/protocol/message/mod.rs
- src/tests/conformance/handshake.rs
- src/tests/conformance/messages.rs
Note: both `zcashd` and `zebra` only close their write half of the connection and don't fully drop the socket when a disconnect is expected (pea2pea doesn't detect the stream close at time of writing: https://github.com/ljedrz/pea2pea/issues/5). The previous version of the tests detected a disconnect because we were using `read_exact` instead of `read` as does pea2pea. I've also updated the spec and pass/fail table to reflect the changes.
Interestingly both `zcashd` and `zebra` also have failing ping/pong tests (if we actually check the `nonce`). 
The synthetic node API is also unstable at this point, though inching closer to something I'm happy with.
> ref: handshake tests with synthetic nodes

- src/tests/resistance/fuzzing_incorrect_checksum.rs
- src/tests/resistance/fuzzing_incorrect_length.rs
They were incorrectly encoding messages as `<body><header>`.
> fix: fuzz generators

- Cargo.toml
- README.md
- SPEC.md
- src/helpers/mod.rs
- src/helpers/synthetic_peers.rs
- src/protocol/message/filter.rs
- src/protocol/message/mod.rs
- src/setup/node.rs
- src/tests/conformance/handshake.rs
- src/tests/conformance/messages.rs
- src/tests/performance/blocks.rs
- src/tests/performance/connections.rs
- src/tests/performance/ping.rs
- src/tests/resistance/fuzzing_corrupted_messages.rs
- src/tests/resistance/fuzzing_flood.rs
- src/tests/resistance/fuzzing_incorrect_checksum.rs
- src/tests/resistance/fuzzing_incorrect_length.rs
- src/tests/resistance/fuzzing_random_bytes.rs
- src/tests/resistance/fuzzing_zeroes.rs
Refactors the conformance tests with the pea2pea backed peers. 
Also includes:
- `tracing` additions to `SyntheticNode::process_message`
- refactored the initial node actions to use a synthetic peer
- removed some dead code
> ref: conformance tests with synthetic nodes

- src/protocol/message/mod.rs
- src/protocol/message/stream_io.rs
- src/protocol/payload/codec.rs
- src/protocol/payload/tx.rs
- src/setup/node.rs
- src/tests/conformance/handshake.rs
- src/tests/conformance/messages.rs
- src/tests/performance/connections.rs
- src/tests/performance/getdata_blocks.rs
- src/tests/performance/ping_pong.rs
- src/tests/resistance/fuzzing_corrupted_messages.rs
- src/tests/resistance/fuzzing_incorrect_checksum.rs
- src/tests/resistance/fuzzing_incorrect_length.rs
- src/tests/resistance/fuzzing_random_bytes.rs
- src/tests/resistance/fuzzing_stress.rs
- src/tests/resistance/fuzzing_zeroes.rs
- src/tools/synthetic_node.rs
Removes `unwrap` in various `Node` functions in favour of returning an `io::Result`. 
Also renames `message::io` -> `message::stream_io` for clarity.
> Improve setup code error handling

- src/setup/config.rs
- src/setup/node.rs
- src/tests/conformance/handshake.rs
- src/tests/conformance/messages.rs
- src/tests/performance/connections.rs
- src/tests/performance/getdata_blocks.rs
- src/tests/performance/ping_pong.rs
- src/tests/resistance/fuzzing_corrupted_messages.rs
- src/tests/resistance/fuzzing_incorrect_checksum.rs
- src/tests/resistance/fuzzing_incorrect_length.rs
- src/tests/resistance/fuzzing_random_bytes.rs
- src/tests/resistance/fuzzing_stress.rs
- src/tests/resistance/fuzzing_zeroes.rs
Removes `unwrap` in various config utility functions. Also addresses a few clippy lints on test targets as a fly-by.
> ref: config error handling

- .github/workflows/test.yml
The fixes for the failing lints are included in #80.
> ci: include tests in clippy checks

- README.md
- src/setup/config.rs
- src/setup/node.rs
The user previously had to specify the location of our generated config file. This change removes this requirement -- since we generate it, we should also pass on the information to the node.
> feat: automated node config path args

- README.md
I'm not certain if this would be enough information for a novice -- but it might be enough for someone familiar with Zebra / ZCashd?
I've also removed the config field for setting the config file in anticipation of #85 getting merged.
> readme: add prerequesite and logging, improve config

- README.md
> fix: a few small readme tweaks

- README.md
- src/setup/config.rs
- src/setup/node.rs
Supersedes #104 and closes #103.
> feat: move configuration and node caches to `~/.ziggurat` directory

- README.md
> docs: descibe `-datadir` start option in readme

- README.md
- src/protocol/message/constants.rs
- src/protocol/payload/mod.rs
Changes the version number to `170_015` and introduces a constant holding the value. This has also been documented in the README. Closes #110.
Branch based on #113, only the last commit is new.
> Feat: update the network protocol version number to Nu5

- fuzz/.gitignore
- fuzz/Cargo.toml
- fuzz/fuzz_targets/decoder.rs
- src/protocol/payload/addr.rs
- src/protocol/payload/codec.rs
- src/protocol/payload/mod.rs
- src/protocol/payload/tx.rs
- src/tools/synthetic_node.rs
This PR adds a `decoder` fuzz target that can be used with `cargo-fuzz` (`cargo +nightly fuzz run decoder`) and a few patches that fix issues that I've found with it, now that the synthetic node can be used outside of tests.
Cc @tuommaki
> Add a fuzz test for the synthetic node impl

- Cargo.toml
- src/tools/metrics/tables.rs
This PR updates the `tabled` dependency. Note: we could consider exporting these metrics to a graphana dashboard in future.
> Deps: update `tabled` to v0.6

- src/tests/performance/connections.rs
- src/tests/resistance/stress_test.rs
Follow-up to #119. Fixes the `tabled` usages in the performance tests that were missed in the previous PR.
> Fix: perf test tabled implementations

- README.md
- src/tests/conformance/handshake/ignore_message_inplace_of_verack.rs
- src/tests/conformance/handshake/ignore_message_inplace_of_version.rs
- src/tests/conformance/handshake/reject_version.rs
- src/tests/conformance/invalid_message/disconnect.rs
- src/tests/conformance/invalid_message/reject.rs
- src/tests/conformance/peering.rs
- src/tests/conformance/query/basic_query.rs
Updates pass/fail for conformance tests against Zebra. Investigations required:
- changes to the peering protocol.
- block/mempool state seeding? 
- comparison with Zcashd behaviour and spec adjustments based on the canonical impl.
> Nu5 retest (Zebra)

- src/setup/node.rs
- src/tests/conformance/handshake/complete_handshake.rs
- src/tests/conformance/handshake/ignore_message_inplace_of_verack.rs
- src/tests/conformance/handshake/ignore_message_inplace_of_version.rs
- src/tests/conformance/handshake/reject_version.rs
- src/tests/conformance/invalid_message/disconnect.rs
- src/tests/conformance/invalid_message/reject.rs
- src/tests/conformance/peering.rs
- src/tests/conformance/query/basic_query.rs
- src/tests/conformance/query/mod.rs
- src/tests/conformance/unsolicited_response.rs
- src/tools/mod.rs
This starts unifying the various timeout constants in the context of conformance tests. In future the same should be done for the performance and resistance tests. They should likely also be made configurable in Ziggurat's configuration file.
> Timeout constant unification for conformance tests

- src/tools/crawler/bin.rs
- src/tools/crawler/mod.rs
- src/tools/crawler/network.rs
- src/tools/crawler/summary.rs
- src/tools/metrics/mod.rs
Moves crawler into a new directory at `/src/tools/crawler/` and separates it between `bin.rs` and `network.rs`.
> Moved crawler to own directory

- src/protocol/message/constants.rs
Adds magic for testnet and mainnet, also bumps protocol version to `170_100`.
> ref: added magic for testnet and mainnet

- Cargo.toml
- src/tools/crawler/main.rs
- src/tools/crawler/mod.rs
- src/tools/crawler/network.rs
- src/tools/crawler/protocol.rs
- src/tools/crawler/summary.rs
- src/tools/mod.rs
Moves crawler to a new binary under `/tools/crawler/`. Also introduces basic integration with `clap` for command-line argument parsing and some minor refactoring.
> Move crawler to bin

- src/protocol/message/constants.rs
- src/tools/crawler/main.rs
Temporarily removes `network` argument from crawler and tweaks magic headers.
> Magic header tweak

- src/tools/crawler/main.rs
- src/tools/crawler/protocol.rs
Refactors connection logic to method, only reconnect if crawler hasn't connected in `RECONNECT_INTERVAL` seconds.
Bumps up `max_connections` to 1000
> Update connection logic

- src/tools/crawler/network.rs
- src/tools/crawler/protocol.rs
Fix for `should_connect` method, `add_addrs` now updates nodes. Introduces `MAX_CONCURRENT_CONNECTIONS` as well.
> Fix for crawler connection check

- src/tools/crawler/main.rs
- src/tools/crawler/protocol.rs
- src/tools/crawler/summary.rs
`NetworkSummary` now takes a reference to Crawler instead and has a new field for number of nodes that identifies themselves with a `Version`.
> Summary tweaking

- SPEC.md
Uses symbolic language to better describe the protocol specifics of conformance and resistance tests. The two performance tests have been left out as their specification is vague (perhaps this should be improved as well).
> Introduce symbolic language for test specification

- src/tools/crawler/main.rs
- src/tools/crawler/metrics.rs
- src/tools/crawler/protocol.rs
Instead of sending requests each iteration, crawler now waits for a response and then starts the main crawling loop. This PR also improves the crawler's general error handling.
> Only send `GetAddr` request once to seed nodes initially

- src/tests/performance/getdata_blocks.rs
- src/tools/synthetic_node.rs
Instead of panicking when node refuses a request from `SyntheticNode`, return an error and abort the handshake. This PR also shuts down nodes after use in `ZG-PERFORMANCE-001`, so we don't clog up the max peer count.
> Don't panic on non-version messages in perf-tests

- Cargo.toml
- src/tools/crawler/main.rs
- src/tools/crawler/metrics.rs
- src/tools/crawler/rpc.rs
Implements a basic, mutually exclusive RPC server as an alternative to file logging. The server has one method, `getmetrics`, that responds with a JSON-serialized `NetworkSummary`. Also adds a two cli arguments for binding and enabling the RPC server.
> Introduce an RPC server for the crawler

- README.md
Updates `zcashd` test results to reflect latest release.
> doc: update `zcashd` test results to `v5.1.0`

- README.md
Updates the `README.md` with new results obtained from testing `zcashd v5.2.0` and `zebra v1.0.0-beta.14`. No major differences.
> doc: test results for new `zcashd` and `zebra` releases

- src/tests/performance/connections.rs
- src/tests/performance/getdata_blocks.rs
- src/tests/performance/ping_pong.rs
- src/tests/resistance/stress_test.rs
- src/tools/metrics/recorder.rs
This PR fixes a number of issues with our current `DebuggingRecorder` implementation. We now take a snapshot separately from querying the values. This fixes an issue in `resistance::stress_test` where we had two sequential `construct_histogram` queries; the initial one would erase state after its use, leading to nil data in our subsequent query. Now that state is handled separately, we also get a minor boost to performance.
> fix: make sure `TestMetrics` doesn't remove state

- SPEC.md
- src/tests/conformance/handshake/complete_handshake.rs
- src/tests/conformance/handshake/ignore_message_inplace_of_verack.rs
- src/tests/conformance/handshake/ignore_message_inplace_of_version.rs
- src/tests/conformance/handshake/reject_version.rs
- src/tests/conformance/invalid_message/disconnect.rs
- src/tests/conformance/invalid_message/reject.rs
- src/tests/conformance/peering.rs
- src/tests/conformance/query/basic_query.rs
- src/tests/conformance/query/get_blocks.rs
- src/tests/conformance/query/get_data.rs
- src/tests/conformance/query/get_headers.rs
- src/tests/conformance/unsolicited_response.rs
- src/tests/performance/connections.rs
- src/tests/performance/getdata_blocks.rs
- src/tests/performance/ping_pong.rs
- src/tests/resistance/corrupt_message/bad_checksum.rs
- src/tests/resistance/corrupt_message/bad_length.rs
- src/tests/resistance/corrupt_message/mod.rs
- src/tests/resistance/corrupt_message/random_payload.rs
- src/tests/resistance/random_bytes.rs
- src/tests/resistance/stress_test.rs
- src/tests/resistance/zeroes.rs
Tests should adhere to the new test naming convention, i.e `id_part_t(subtest_no)_(message type)_(extra_test_desc)`.
Progress:
> Adhere to new test naming convention

- .github/workflows/crawler.yml
This PR introduces a new CI workflow wherein we crawl the network for ~30 min, logging each run under a new subdirectory: `results/crawler`.
> Introduce crawler workflow

- .github/workflows/crawler.yml
- .github/workflows/zcashd-nightly.yml
- .github/workflows/zebra.yml
Similarly to `zcashd`, this PR introduces a new workflow for running `zebra` nodes through the suite. Results are logged as before, but now under a new subdirectory path per node, i.e `results/zcashd` for `zcashd` and `results/zebra` for `zebra`. The PR also migrates the previous trigger-on-push behaviour to schedule runs each day. As an added bonus, this PR also fixes a small issue that prevented the workflow from also logging the `latest.jsonl`.
> Introduce ci for zebra

- .github/workflows/crawler.yml
- .github/workflows/test.yml
- .github/workflows/zcashd-nightly.yml
- .github/workflows/zcashd.yml
- .github/workflows/zebra.yml
With the somewhat recent announcement of deprecating Node 12 in favor of Node 16, we should update our dependencies to their latest versions. See [this post](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) for more details regarding the change. Also note that, `actions-rs` actions have not gotten updates in quite a while and still run on Node 12.
> Update CI dependencies

- .github/workflows/crawler.yml
- .github/workflows/test.yml
- .github/workflows/zcashd-nightly.yml
- .github/workflows/zebra.yml
Replaces all the `actions-rs` actions with standard `rustup/cargo` commands now that `actions-rs` is no longer maintained.
> deps(ci): remove `actions-rs`

- .github/workflows/crawler.yml
- .github/workflows/zcashd-nightly.yml
- .github/workflows/zebra.yml
This PR modifies the test runners + crawler workflow to compress the results before committing. This **should not** affect the GUI, given that the latest result (`latest.jsonl`) will still be kept uncompressed.
> feat(ci): compress results

- Cargo.toml
- src/tools/crawler/metrics.rs
I've updated the zcash crawler to use:
- new spectre API to fetch indices
- remove AGraph as struct, using updated NetworkSummary
I have run the zcash crawler per normal, and got a correctly formed sample.json back (e.g., using the `indices` field in NetworkSummary, rather than `agraph`.
> feat: update crawler to use latest NetworkSummary & spectre

- src/tools/crawler/rpc.rs
This should solve the problem discovered by Piotr with empty crawler responses due to response size exceeding server maximum.
> feat: increase crawler's max response size from 20MB to 200MB

- src/tools/crawler/main.rs
- src/tools/crawler/metrics.rs
`crawler_runtime` is currently calculated before a function (`get_filtered_adjacency_indices`) that takes a long time to compute, resulting in skewed runtime results. This PR makes sure that `crawler_runtime` only gets procured when returning `NetworkSummary`, and adds a small `info!` line in the summary calculation loop for displaying time taken to run the calculations.
> fix: always procure crawler runtime last

- .github/workflows/crawler.yml
- Grep for `error` in `latest.json` and fail workflow if it is found.
- Move some commands into a new step for processing data for added clarity.
> Fail crawler workflow if an error code is returned

- .github/workflows/zcashd-nightly.yml
- .github/workflows/zebra.yml
Included with this PR (identical to the `XRPL` one), for both `zcashd` and `zebra`:
- A new step that will display the output of the diff command between the workflows latest run (latest.jsonl) and the one prior to that (comparison.jsonl)
- The json files are modified in a new function, filter_json, to filter out things that would clog the output of diff, e.g exec_time and type.
> feat(ci): display diff from last run

- .github/workflows/build-zcashd.yml
- .github/workflows/crawler.yml
- .github/workflows/diff-with-previous.yml
- .github/workflows/install-zcashd.yml
- .github/workflows/process-results.yml
- .github/workflows/zcashd-nightly.yml
- .github/workflows/zebra.yml
- New `install-zcashd` workflow
- Split `process-results` into, `process-results` and `diff-with-previous`
- Modifies `process-results` to be compatible with calls from crawler workflows
> Introduce more CI reusability

- .github/workflows/crawler.yml
- .github/workflows/process-results.yml
Crawler workflows uses `.json` files, while suite workflows uses `.jsonl` files. This PR allows both extensions to be used in the `process-results` workflow.
> Allow different file extensions in `process-results`

- .github/workflows/build-ziggurat.yml
Unit tests get compiled under namespace `ziggurat_` on XRPL impl, while they, under the Zcash impl, compiles under `ziggurat-`. This PR simply adjusts the placement of the wildcard to adjust for that.
> fix(ci): modify wildcard placement

- Cargo.toml
- src/protocol/payload/version.rs
- src/tools/crawler/metrics.rs
- src/tools/crawler/network.rs
- src/tools/crawler/protocol.rs
Allow recognize type of network for each node. Currently it allows to check if node is from real ZCash network or from any other.
Classification is based on three factors:
start_height - this MUST match
port
agent string
If either port or agent string would not match node still can be considered as ZCash node as long as start_height matches. The only exception is when agent string identifies node as version 6 (which is other network than ZCash) - that is blocker and even when two other conditions are met, node wouldn't be considered as valid ZCash node.
> feat: node network checker

- Cargo.toml
- src/setup/node.rs
- src/tests/idle_node_in_the_background.rs
- src/tests/mod.rs
This PR introduces development tests for tinkering, similar to the ones already existing in XRPL.
The tests have support for a number of different configuration options, these are:
- enable/disable node's logs to stdout
- enable/disable tracing
- enable/disable attaching a single synthetic node to the node
- suboption: choose the initiator for the connection
> feat: development tests

- .github/workflows/check-and-lint.yml
Since development tests are not meant to be run without a compiled node instance, we have to ignore them in `check-and-lint` by ~~explicitly testing under the namespace `protocol::payload`~~ appending `--skip dev` to the command.
> chore: ignore dev tests in check

- src/tools/synthetic_node.rs
```
chore: log connection info during the handshake
We should be able to see more info in the logs regarding our new
connection.
```
A second and an extra commit which I needed for some local tests:
```
feat(synth_node): add disconnect function
```
> More info in the logs about the new connection during handshake

- src/tools/crawler/main.rs
- src/tools/crawler/network.rs
- src/tools/crawler/protocol.rs
This feature changes crawler behavior - till this commit, crawler connected to the peer, grab first addr message and instantly disconnected. Now, crawler waits for the first addr message that contains more than one address OR addr message with one address but different from the peer source address.
Waiting for addr message implies that crawler has to manage connected nodes - it's done using additional field in known_network structure. Connections are managed from the main loop - old connected nodes are disconnected after specified timeout (180 s).
Waiting for addr message makes crawler work slower. There can be observed more "waves" where connections are made and then, some waves where crawler prints it cannot make new connections due to connection limit reached. However, those hosts …
> feat: crawler waits for addr message for given timeout

- .github/workflows/README.md
- .github/workflows/crawler.yml
- Crawler now enters the network via nodes fetched from DNS instead of compiling a local node and entering that way.
> ci(crawler): use dns-seed instead of compiling local node

- Cargo.lock
- Cargo.toml
Upgrades trivial dependencies:
```
async-trait 0.1.53 -> 0.1.68
home 0.5.3 -> 0.5.5
metrics 0.20.0 -> 0.21.0
metrics-util 0.15.0
pea2pea 0.45 -> 0.46
toml 0.6.0 -> 0.7.3
clap 4.1.4 -> 4.2.5
```
Also removes the patch part of the SemVer for each package.
*Note:* `tabled` and `jsonrpsee` have new versions available but were not upgraded, since they introduce breaking changes.
> deps: update trivial

- .github/workflows/crawler.yml
- src/tools/crawler/README.md
- src/tools/crawler/main.rs
- IP addresses/DNS servers are now given with the same CLI argument, `--seed-addrs`.
- Crawler will first try to parse an argument as a `SocketAddr`, if that fails it will try a DNS lookup instead.
- Also included are accompanying docs and workflow changes.
> ref: use seed-addrs for both standalone ips and dns

- src/protocol/message/constants.rs
- src/tools/crawler/main.rs
- Crawler can now parse all permutations of inputted `seed-addrs`. These are:
- IP + port (both IPv4 and IPv6 are valid)
- IP (Default port will be appended)
- DNS + Port (Will do a lookup on DNS and remember the port)
- DNS (Default port will be appended)
> chore: correctly parse all permutations of ip/dns

- src/protocol/message/constants.rs
- src/protocol/message/mod.rs
Synth node may sometimes fail because of alert messages sent by ancient real nodes. Since alert messages have been deprecated since long ago, we ignore them.
> feat: alert message type

- .github/workflows/crawler.yml
We don't run zcashd in the background so we don't need to kill it after the crawling is over.
> ci: remove obsolete line

- src/protocol/payload/block.rs
- src/protocol/payload/inv.rs
- src/protocol/payload/tx.rs
- src/tests/conformance/invalid_message/disconnect.rs
- src/tests/conformance/query/get_data.rs
Ensures that our synth node binary (or a crawler) won't die within a few seconds after performing a handshake with zebrad
>  feat: support for WtxMxg type in InvHash 

- Cargo.lock
- src/tools/synthetic_node.rs
- synth_node_bin/Cargo.lock
- synth_node_bin/src/main.rs
Updated synth_node_bin default action to run the synth node indefinitely until the connection is dropped.
The new version of the synth node is resistant to panicking, so when the `stubborn` argument is used, it will run forever.
For this purpose, in the synth_node.rs a new API has been introduced which won't panic in case of failure but will return an `Err` instead:
```rust
/// Reads a message from the inbound (internal) queue of the node.
/// In case of channel failure, it returns an [`ConnectionError`].
///
/// Messages are sent to the queue when unfiltered by the message filter.
pub async fn try_recv_message(&mut self) -> Result<(SocketAddr, Message), ConnectionError>
```
> chore: update synth_node_bin's default action 

- .github/workflows/crawler.yml
Also adds `workflow_dipsatch` so we can manually trigger the workflow.
> ci: run crawler on self-hosted machine

- .github/workflows/zcashd-nightly.yml
- .github/workflows/zebra.yml
`previous-result` is no longer stored by the repo, so we can't fetch it from there.
> ci: only upload `latest-result`

- .github/workflows/zcashd-nightly.yml
- .github/workflows/zebra.yml
- Supply secrets to `diff-with-latest` step so it can download the previous result.
- Updates build artifact name to be correct.
> ci: supply secrets to `diff-with-latest`

- src/tools/crawler/main.rs
- src/tools/crawler/protocol.rs
During tests some of the peers have been observed to have delays (massive!) in sending first Version message.
Till that commit crawler:
1) had degenerated handshake procedure - it was waiting only for crawler to send version and returned success;
2) had hardcoded 1 sec sleep after successfull connect() and after that it just sent GetAddr message.
The above resulted in situations, where GetAddr was sent before the remote party sent crawler version message. It leads to dropping GetAddr message as the protocol standard says that there can be no other communication before exchanging Version messages.
This commit removes hardcodes and make crawler fit into protocol standard. Now GetAddr messages are sent only after crawler receives Version message from the remote party. That allows to wait …
> chore: wait for Version message before sending GetAddr

- .github/workflows/zcashd-nightly.yml
- .github/workflows/zebra.yml
(Closes #240)
Diffing is handled easier in the GUI, thus we remove this step from the workflows.
> ci: remove `diff-with-previous` step

- src/tools/crawler/README.md
- src/tools/crawler/main.rs
- src/tools/crawler/metrics.rs
Add new command line argument which allows user to specify default port to be used with seeds with no port specified. It allows running crawler both with mainnet and testnet as well as nodes running on non-standard ports.
Note: there is still a need to change network MAGIC value to switch between mainnet and testnet.
> feat: add default_port argument to crawler command line

- synth_node_bin/Cargo.lock
- synth_node_bin/Cargo.toml
- synth_node_bin/src/action/mod.rs
- synth_node_bin/src/action/send_get_addr_and_forever_sleep.rs
- synth_node_bin/src/main.rs
A synth node binary should have an easy way to add new actions. This implementation provides action plugin support so that all different actions can be added under different modules under the `src/action/` directory.
> refactor(synth_node_bin): support multiple actions

- src/protocol/payload/tx.rs
- src/tools/synthetic_node.rs
Three fixes/refactors correcting our node's behavior when processing `tx` structures.
There are following changes:
1. Change max frame length to 1MB. There has been observed frames bigger than currently set limit.
For example sending request (using getdata message) to obtain informationabout the block:
`[53, 232, 24, 104, 196, 154, 85, 106, 186, 216, 58, 134, 35, 37, 5, 230, 98, 51, 164, 248, 91, 6, 223, 175, 92, 57, 245, 211, 56, 50, 100, 0]`
from testnet will result in a reply (block command) which is 627412 bytes.
Standard defines that length field in MessageStructure is uint32_t so the maximum frame size can be really big.
tokio_util::codec max frame length default value is 8 MB.
Extended max frame length to 1MB to have some space in case of bigger frames (which are rare) and not …
> chore: tx corrections

- src/tools/synthetic_node.rs
- synth_node_bin/src/action/advanced_sn_for_s001.rs
- synth_node_bin/src/action/mod.rs
- synth_node_bin/src/action/send_get_addr_and_forever_sleep.rs
- synth_node_bin/src/main.rs
Commits with info about the change:
```
feat(synth_node_bin): add advanced SN for s001
A synth_node_bin with this action can:
- listen for inbound connections and print connection status periodically
- periodically send GetAddr/Ping/Addr messages to all connected peers
```
```
feat(synthetic_node): add connected_peer_infos API
```
```
feat(synth_node_bin): support for action preconfig
- It should be possible to configure the action settings before the
action is even started in some cases.
```
There's one more TODO in the code regarding the listening address, which needs to be fed to the synth_node builder - which will be done in a separate PR.
> feat(synth_node_bin): add advanced SN for s001

- synth_node_bin/src/action/mod.rs
- synth_node_bin/src/action/quick_connect_and_then_clean_disconnect.rs
The action quickly connects and then cleanly disconnects.
The word `clean` is used here because one more similar action will be added where we will skip the disconnect API on the synth node side.
> feat(synth_node_bin): new action for quick connect/disconnect

- synth_node_bin/src/action/mod.rs
- synth_node_bin/src/main.rs
With this change the action can be chosen during the startup of the process.
New help text output:
```
A synthetic node which can connect to the node and preform some actions independently
Usage: synth_node_bin [OPTIONS]
Options:
-n, --node-addr <NODE_ADDR>      An address of the node in the <ip>:<port> format
-s, --stubborn                   Always reconnect in the case the connection fails - synthetic node never dies
-t, --tracing                    Enable tracing
-a, --action-type <ACTION_TYPE>  Possible actions: SendGetAddrAndForeverSleep / AdvancedSnForS001 / QuickConnectAndThenCleanDisconnect [default: SendGetAddrAndForeverSleep]
-h, --help                       Print help
-V, --version                    Print version
```
> feat(synth_node_bin): add arg for action selection

- synth_node_bin/src/action/advanced_sn_for_s001.rs
- synth_node_bin/src/action/constantly_ask_for_random_blocks.rs
- synth_node_bin/src/action/mod.rs
- synth_node_bin/src/action/quick_connect_with_improper_disconnect.rs
- synth_node_bin/src/main.rs
This new action is pretty similar to the existing one, but in this case, the socket is not closed properly.
commits:
```
feat(synth_node_bin): new variant of connect/disconnect action
The action quickly connects and then disconnects without closing the
socket properly.
```
```
feat(synth_node_bin): action cfg allow_shutdown option
```
> feat(synth_node_bin): new variant for the connect/disconnect action

- synth_node_bin/scripts/run_sn.sh
A simple script for deploying multiple synth_node_bin.
It is nothing official, so it's not very well documented - since it's for our internal usage.
Lots of things are hardcoded in the script, but it can be easily modified on the fly.
It's like a simple template.
> feat(synth_node_bin): add a wrapper debug script
