- src/tests/conformance/handshake.rs
Removes a lot of the code bloat induced by nested matches. 
Also added a helper function to determine connection error.
> refactor: replace nested matches with early exits

- src/protocol/message.rs
- src/protocol/payload/block.rs
This PR introduces Block message encoding/decoding and sets up Tx message handling.
> Implement block encoding and decoding

- src/tests/conformance/messages.rs
Tests that a node ignores unsolicited response messages, and does not terminate the connection.
> feat: added conformance test 009

- .github/workflows/test.yml
- src/protocol/message.rs
- src/protocol/payload/addr.rs
- src/tests/conformance/messages.rs
Check Ziggurat unit tests (aka ignored tests), clippy and rustfmt (nightly).
> feat: check unit tests and lints on CI

- src/protocol/payload/addr.rs
The chrono timestamp is `i64` but the protocol should encode it as `u32`
> fix: timestamp codec is i64 instead of u32

- src/protocol/payload/block.rs
- src/protocol/payload/mod.rs
I'm not totally stoked about the naming of the hash function - `double_hash`.
> feat: added block hashing

- src/protocol/payload/block.rs
- src/protocol/payload/mod.rs
- src/setup/config.rs
A variety of minor additions and changes. Feel free to challenge any of them.
Most of them are required in the future (I've been using them in temporary test snippets, but never ended up committing them).
> variety_changes

- src/protocol/payload/block.rs
Added extra codec functions for Header which excludes the `tx_count`.
These can then be used by Block and Hash functions, freeing up the
normal codec functions for normal use. This enables Vec<Header> codecs.
> feat: improve header codec

- README.md
- src/tests/resistance/fuzzing.rs
Some cases are tbd as they require more in-depth investigations.
> test: resistance-005

- README.md
- src/protocol/message.rs
- src/protocol/payload/filter.rs
- src/protocol/payload/mod.rs
- src/protocol/payload/reject.rs
- src/tests/conformance/messages.rs
The bloom filter messages still get flagged as Malformed by zcashd. *shrugs*
> conformance 008

- src/tests/resistance/fuzzing.rs
> doc: fuzz test comments

- Cargo.toml
- README.md
- src/protocol/payload/version.rs
- src/tests/conformance/handshake.rs
- src/tests/resistance/fuzzing.rs
I still need to implement the missing message types. Thought I'd first get it on par with the rest before we add / refactor the rest of the message types.
> Added resistance test cases 003 and 004

- src/tests/conformance/messages.rs
Previously tested that inbound addresses were gossiped.
- Now correctly tests that only peer listener addresses get gossiped
- Exercises known Zebra bug: https://github.com/ZcashFoundation/zebra/pull/2120
> fix: conformance test 013

- README.md
- SPEC.md
- src/tests/conformance/handshake.rs
- src/tests/conformance/messages.rs
- src/tests/performance/blocks.rs
- src/tests/resistance/fuzzing_corrupted_messages.rs
- src/tests/resistance/fuzzing_incorrect_length.rs
- fresh test run of latest zebra / zcashd
- update the result comments
- improve readme test table with finer granularity
- minor fixes
> test overhaul

- src/tests/resistance/fuzzing_incorrect_checksum.rs
- src/tests/resistance/fuzzing_incorrect_length.rs
> fix: fuzz generators not appending payload

- src/tests/performance/connections.rs
The test now enforces a timeout (which fixes Zebra hanging).
Now it causes connection bind failures instead, which get logged as
errors in the stats.
> fix: connection performance test

- README.md
- src/protocol/payload/addr.rs
- src/protocol/payload/block.rs
- src/protocol/payload/codec.rs
- src/protocol/payload/filter.rs
- src/protocol/payload/inv.rs
- src/protocol/payload/mod.rs
- src/protocol/payload/reject.rs
- src/protocol/payload/tx.rs
- src/protocol/payload/version.rs
> More documentation improvements

- src/setup/node.rs
- src/tests/conformance/handshake.rs
- src/tests/conformance/messages.rs
- src/tests/performance/connections.rs
- src/tests/performance/getdata_blocks.rs
- src/tests/performance/ping_pong.rs
- src/tests/resistance/corrupt_message/bad_checksum.rs
- src/tests/resistance/corrupt_message/bad_length.rs
- src/tests/resistance/corrupt_message/mod.rs
- src/tests/resistance/corrupt_message/random_payload.rs
- src/tests/resistance/random_bytes.rs
- src/tests/resistance/stress_test.rs
- src/tests/resistance/zeroes.rs
This lets us more strongly guarantee that the Node process will get killed.
Also fixed some panic's in Node setup and stop.
> feat: implement drop for node

- src/tests/conformance/invalid_message.rs
- src/tests/conformance/messages.rs
- src/tests/conformance/mod.rs
- src/tests/conformance/unsolicited_response.rs
> ref: split ignores_unsolicited_responses

- src/protocol/payload/tx.rs
See: https://zips.z.cash/protocol/protocol.pdf#networkupgrades
> Feat: Nu5 Tx (v5) updates

- .rustfmt.toml
- src/protocol/message/mod.rs
- src/protocol/payload/addr.rs
- src/protocol/payload/block.rs
- src/protocol/payload/codec.rs
- src/protocol/payload/filter.rs
- src/protocol/payload/inv.rs
- src/protocol/payload/mod.rs
- src/protocol/payload/reject.rs
- src/protocol/payload/tx.rs
- src/protocol/payload/version.rs
- src/setup/config.rs
- src/setup/node.rs
- src/tests/conformance/handshake/ignore_message_inplace_of_version.rs
- src/tests/conformance/handshake/reject_version.rs
- src/tests/conformance/peering.rs
- src/tests/conformance/query/basic_query.rs
- src/tests/performance/connections.rs
- src/tests/performance/getdata_blocks.rs
- src/tests/resistance/corrupt_message/bad_checksum.rs
- src/tests/resistance/corrupt_message/bad_length.rs
- src/tests/resistance/corrupt_message/mod.rs
- src/tests/resistance/corrupt_message/random_payload.rs
- src/tests/resistance/random_bytes.rs
- src/tests/resistance/stress_test.rs
- src/tests/resistance/zeroes.rs
- src/tools/fuzzing.rs
- src/tools/synthetic_node.rs
Adds the `group_imports = "StdExternalCrate"`.
> Fmt: group imports

- src/tools/crawler.rs
Removes `listener_ip` from the config of `Crawler` so we don't collect duplicate nodes, for now it also provides a fake `SocketAddr` during the handshake.
> Disable Crawler's listener ip

- src/tools/crawler.rs
`KnownNode` now also keeps track of `protocol_version`, `user_agent` and `services`, updated once `Crawler` receives a `Message::Version`.
> Add more metrics to network crawler

- src/protocol/payload/mod.rs
- src/tools/crawler.rs
- src/tools/metrics/mod.rs
- src/tools/metrics/summary.rs
Introduces a basic network summary which logs network metrics to a log file.
> Added a network summary

- Cargo.toml
https://doc.rust-lang.org/edition-guide/editions/index.html
> Update to Rust edition 2021

- Cargo.toml
- src/tools/crawler/main.rs
- src/tools/crawler/network.rs
- src/tools/crawler/protocol.rs
- src/tools/crawler/summary.rs
Implements new network graph metrics and fixes a few runtime errors.
> Introduce network graph metrics

- src/tools/crawler/main.rs
- src/tools/crawler/metrics.rs
- src/tools/crawler/network.rs
Now creates `Graph` only once and updates it progressively.
> Reuse existing metrics graph

- README.md
Includes parameter download as an install step.
> doc: update zebra install instructions

- README.md
Updated results for `Zcashd v5.0.0` and `Zebra 1.0.0-beta.12`
> doc: update test results

- src/tests/conformance/handshake/ignore_message_inplace_of_verack.rs
- src/tests/conformance/handshake/ignore_message_inplace_of_version.rs
Updated comments regarding test results for new `zebra` release.
> doc: update zebra results in tests

- src/tools/crawler/protocol.rs
Removes connection attempts on peer list. Also optimizes how crawler connects to peers in the main loop, accounting for max allowed connections.
> tweak: optimize how crawler connects to peers

- .github/workflows/test.yml
Might be worth looking into setting up a matrix with the feature flags in future.
> ci: add job to check the crawler

- src/tools/crawler/main.rs
Introduces new summary creation loop interval constant and makes sure that the loop happens consistently, regardless of time taken to calculate metrics.
> Make sure summary creation is consistent to loop interval

- src/tools/crawler/README.md
Update crawler `README.md` with more information on how it works.
> doc: update crawler `README.md`

- .github/workflows/crawler.yml
- .github/workflows/zcashd-nightly.yml
- .github/workflows/zebra.yml
This PR fixes an issue that occurred when storing dates in environment variables. It also features a rename of `Zebra` -> `zebra`.
> ci: store date in shell variable

- Cargo.toml
- src/tools/crawler/main.rs
- src/tools/crawler/metrics.rs
- src/tools/crawler/network.rs
- src/tools/crawler/rpc.rs
* Use NetworkSummary from ziggurat-core
> refactor: use ziggurat-core for crawler

- Cargo.toml
- src/tools/crawler/metrics.rs
- src/tools/crawler/network.rs
* Use newest ziggurat-core-crawler
* Refactor out method to add new nodes based on connections
> refactor: use IpAddr only to represent a connection

- Cargo.toml
- src/tools/crawler/metrics.rs
- src/tools/crawler/network.rs
next step in refactoring the crawler metrics.
> feat: update to latest ziggurat-core, SocketAddr, NodesIndices

- .github/workflows/crawler.yml
- .github/workflows/zcashd-nightly.yml
- .github/workflows/zebra.yml
This PR:
- Adjusts git user in workflows
- Refactors some names here and there
> chore(ci): adjust git user

- .github/workflows/process-results.yml
- .github/workflows/zcashd-nightly.yml
- .github/workflows/zebra.yml
Moves shared code into a new workflow file, `process-results.yml`.
> chore: reuse workflow

- .github/workflows/build-ziggurat.yml
- .github/workflows/zcashd-nightly.yml
- .github/workflows/zebra.yml
- New workflow for compiling unit tests, further reducing code duplication.
> ref: `build-ziggurat` workflow

- .github/workflows/README.md
- Adds a short section explaining the `check-and-lint` workflow.
> doc(ci): check and lint section

- .github/workflows/crawler.yml
Related to https://github.com/runziggurat/ziggurat-core/pull/41
> Call ziggurat-core:build-viz-state workflow after crawl.

- .github/workflows/crawler.yml
Related to https://github.com/runziggurat/ziggurat-core/pull/42
> Use filter 'Zcash' for the crunchy commad.

- src/protocol/payload/mod.rs
- synth_node_bin/Cargo.lock
- synth_node_bin/Cargo.toml
- synth_node_bin/src/action/constantly_ask_for_random_blocks.rs
- synth_node_bin/src/action/mod.rs
Intended to be used with file with block hashes (JSON file) grabbed either from mainnet or testnet.
> feat: add new action which constantly ask for random blocks using getdata command

- .github/workflows/build-zcashd.yml
- .github/workflows/zcashd-nightly.yml
- .github/workflows/zebra.yml
- Implements runziggurat/ziggurat-core#52
> Grab node metadata

- src/tools/synthetic_node.rs
- synth_node_bin/src/action/advanced_sn_for_s001.rs
- synth_node_bin/src/action/constantly_ask_for_random_blocks.rs
- synth_node_bin/src/action/mod.rs
- synth_node_bin/src/action/quick_connect_and_then_clean_disconnect.rs
- synth_node_bin/src/action/quick_connect_with_improper_disconnect.rs
- synth_node_bin/src/action/rt_s1_collector.rs
- synth_node_bin/src/action/send_get_addr_and_forever_sleep.rs
- synth_node_bin/src/main.rs
```
chore: make synthetic node more robust
```
```
refactor(synth_node_bin): make address arg optional
```
```
feat(synth_node_bin): Add collector action
A node which sends an Addr message every three seconds containing all
connected peers and their listening ports.
```
> feat(synth_node_bin): Add collector action 

- synth_node_bin/src/action/constantly_ask_for_random_blocks.rs
Add printing statistics for each n blocks requested.
> chore: add printing statistics each n blocks

- synth_node_bin/src/action/mod.rs
- synth_node_bin/src/action/rt_s1_tainter.rs
- synth_node_bin/src/main.rs
```
feat(synth_node_bin): add desired_listening_port arg
```
```
feat(synth_node_bin): add rt S1 tainter action
- a listener node which sends a tainted Addr message to all its peers
```
>  feat(synth_node_bin): add rt S1 tainter action 

- synth_node_bin/src/action/constantly_ask_for_random_blocks.rs
Tests showed that sleep is not needed anymore.
> chore: remove sleep as tests showed it's not needed anymore
